### ISSUE TITLE
Handle missing table error conditions

### ISSUE THREAD

**Issue by TGPSKI** [app-sre/gabi#5]
If not handled properly, go will panic `invalid memory address or nil pointer dereference`

See comment: https://github.com/app-sre/gabi/pull/4#discussion_r667266599

**Comment by TGPSKI** [comment]
Golang's lack of try/except blocks may be challenging for us here. Need to investigate ways to catch this type of error so we can give feedback to the requester.

**Comment by rrati** [comment]
defer + recover may be what you want:
https://golang.org/ref/spec#Handling_panics

**Comment by suzana-nesic** [comment]
Looks like it was resolved from this commit: https://github.com/app-sre/gabi/commit/b4be98ac40fe91c7911f4347339b8ddc7db9e0ee

Output for a missing table now shows: `ERROR: relation "tablenothere" does not exist (SQLSTATE 42P01)`
